export const symptomOptions = [
  "Fatigue / Low energy",
  "Polyuria (frequent urination)",
  "Unexplained weight loss",
  "Excessive thirst",
  "Blurred vision",
  "Slow wound healing",
  "Tingling in hands or feet",
  "Shortness of breath",
  "Chest discomfort",
  "Dizziness",
  "Polyphagia (excessive hunger)",
  "Dry mouth",
  "Headaches",
  "Nausea or vomiting",
  "Fruity / acetone breath",
  "Nightmares or night sweats",
  "Palpitations / rapid heartbeat",
  "Confusion / difficulty concentrating",
  "Foot ulcers or sores not healing",
  "Foamy or frothy urine (proteinuria)",
];
